version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rust-graphql-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: {}
